[tool.poetry]
name = "shape_drawer"
version = "1.0.0"
description = "Demo App"
authors = ["Tom Fynes"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
